trigger:
- main

pool:
  name: default
  demands: 2021.1.9f1

steps:
- task: UnityBuildTask@3
  name: unitybuild
  inputs:
    buildTarget: standalone
    outputPath: $(Build.BinariesDirectory)
    outputFileName: drop

- script: |
    echo $(unitybuild.logsOutputPath)
