trigger:
- master

pool:
      name: Unity_Agent_Local_Machine_Anurag
     

steps:
- checkout: self
  lfs: true
  
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.BinariesDirectory)
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    OverWrite: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: Build Output'
  inputs:
    targetPath: '$(Build.BinariesDirectory)'
    artifact: build