# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Unity_Agent_Local_Machine_Anurag
  demands:  Unity_2021.2.3f1

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Win64'
    unityEditorsPathMode: 'specify'
    customUnityEditorsPath: 'D:\Unity_Installed\2021.2.3f1\Editor'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'Build'